# Dark
set -g @status-bg "#16161e"
set -g @border-fg "#414868"
set -g @inactive-window-bg "#181821"
set -g @active-window-bg "#1a1b26"
set -g @status-fg "#a9b1d6"
set -g @status-session-bg "#9ece6a"
set -g @status-current-window-bg "#7dcfff"
set -g @inactive-window-fg "#bcc4c4"
