set -g @status-bg "#D4D4D4"
set -g @border-fg "#a89984"
set -g @inactive-window-bg "#ECEAE6"
set -g @active-window-bg "#F0EFEC"
set -g @status-fg "#3c3836"
set -g @status-session-bg "#98971a"
set -g @status-current-window-bg "#458588"
set -g @inactive-window-fg "#33374c"
