format = """
$directory$git_branch
$character
"""

[directory]
style = "fg:#2D3144"
truncation_length = 7
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
symbol = ""
style = "fg:#06652a"
format = "[$branch]($style) "

[character]
success_symbol = "[❯](fg:#2d539e)"
error_symbol = "[❯](fg:#cc517a)"
vicmd_symbol = "[❯](fg:#3a3f55)"
